# Generated by Django 2.2.6 on 2019-10-27 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20191027_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 10, 27, 14, 12, 26, 468565, tzinfo=utc))),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor')),
            ],
        ),
    ]
